---
- name: 'Update e upgrade apt packages'
  become: true
  apt:
    upgrade: yes
    update_cache: yes
  cache_valid_time: 86400 #One day

- name: 'Instala pacotes de dependencia do sistema operacional'
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - mysql-server-5.6
    - python-mysqldb

- name: 'Cria o banco do MySQL'
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    # login_password: root
    state: present

- name: 'Cria o usuario do MySQL'
  mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: "{{ wp_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL,GRANT"
    state: present
    host: "{{ item }}"
  with_items:
    - "{{ wp_host_ip }}"

- name: 'Configura MySQL para aceitar conexoes remotas'
  copy:
    src: 'files/my.cnf'
    dest: '/etc/mysql/my.cnf'
  become: yes
  notify:
    - restart mysql
